# Generated by Django 5.0.2 on 2024-02-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(default='student', max_length=15),
        ),
    ]
