# Generated by Django 5.0.2 on 2024-02-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher',
            new_name='teach',
        ),
    ]
